@startuml
left to right direction
skinparam packageStyle rectangle
:Player: as player
:Organiser: as org
:Team Manager: as tm
rectangle "InterIIT Management system" {
(Login as\nPlayer) as plogin
(Login as\nOrganiser) as ologin
(Login as\nTeam manager) as tlogin
(Authenticate) as auth
(View Sports\nSchedule) as vschedule
(View Sports\nScoreboard) as vscore
(Update \nScoreboard) as cscore
(Change \n Schedule) as cschedule
(Reset \n Credentials) as reset
player -- plogin
org -- ologin
tm -- tlogin
plogin ..> auth: "<<include>>"
reset ..> plogin : "<<extend>>"
vschedule ..> plogin : "<<extend>>"
vscore ..> plogin : "<<extend>>"
tlogin ..> auth : "<<include>>"
reset ..> tlogin : "<<extend>>"
reset ..> auth : "<<include>>"
ologin ..> auth : "<<include>>"
reset ..> ologin : "<<extend>>"
vschedule ..> ologin : "<<extend>>"
vscore ..> ologin : "<<extend>>"
cschedule ..> ologin : "<<extend>>"
cscore ..> ologin : "<<extend>>"
}
@enduml
